plot_file = fopen('vipplot.vgf', 'a')
fprintf(plot_file, '# color 255 0 0\n')
fclose(plot_file)
plot_file = fopen('vipplot2.vgf', 'a')
fprintf(plot_file, '# color 0 255 0\n')
fclose(plot_file)
plot_file = fopen('vipplot3.vgf', 'a')
fprintf(plot_file, '# color 0 0 255\n')
fclose(plot_file)
